# this sets the logger level (true = info, false = debug)
production: false
#The eoa address of Operato, used for sending transactions
operator_address: 0xce5b680d1fd259ada4820e9314bcf0723bdb1287
#The eoa address of avs owner, used for sending transactions
avs_owner_address: 0x3e108c058e8066DA635321Dc3018294cA82ddEdf
#Address of deployed AVS contract
avs_address: 0x830ED4c9a8b412905EBd75aAC72CBED65ce49309

# ETH RPC URL
eth_rpc_url: http://127.0.0.1:8545
eth_ws_url: ws://127.0.0.1:8546
avs_ecdsa_private_key_store_path: tests/keys/avs.ecdsa.key.json
operator_ecdsa_private_key_store_path: tests/keys/operator.ecdsa.key.json
bls_private_key_store_path: tests/keys/test.bls.key.json
node_api_ip_port_address: 0.0.0.0:9010
enable_node_api: true
register_operator_on_startup: false
  
#register avs parameters
min_stake_amount: 1
avs_owner_addresses:
  - "exo18cggcpvwspnd5c6ny8wrqxpffj5zmhklprtnph"
  - "exo1sc9kjykz6qehauzmhjympsktdjaw4d99dksgrk"
asset_ids:
  - "0xdac17f958d2ee523a2206206994597c13d831ec7_0x65"
  - "0xdac17f958d2ee523a2206206994597c13d831ec7_0x64"
avs_unbonding_period: 7
min_self_delegation: 0
epoch_identifier: hour
avs_reward_address: 0x0000000000000000000000000000000000000000
avs_slash_address:  0x0000000000000000000000000000000000000000
params:
  - 5
  - 7
  - 8
  - 4
