# this sets the logger level (true = info, false = debug)
production: false
#The eoa address of Operato, used for sending transactions
operator_address: 0x02c63ae8aa779c328e077ff895ee0b9c36e463ff
#Addresses of deployed AVS contract
avs_address: 0x10Ed22D975453A5D4031440D51624552E4f204D5
# ETH RPC URL
eth_rpc_url: http://127.0.0.1:8545
eth_ws_url: ws://127.0.0.1:8546
operator_ecdsa_private_key_store_path: tests/keys/operator2.ecdsa.key.json
bls_private_key_store_path: tests/keys/bls2.key.json
node_api_ip_port_address: 0.0.0.0:9010
enable_node_api: false
register_operator_on_startup: true

# depoist and delegate params
deposit_amount: 100
delegate_amount: 100
staker: 0xa53f68563D22EB0dAFAA871b6C08a6852f91d627